apiVersion: 1

datasources:
  - name: ClickHouse
    type: vertamedia-clickhouse-datasource
    uid: clickhouse
    url: http://clickhouse-local:8123
    access: proxy
    database: analytics
    isDefault: true
    basicAuth: true
    basicAuthUser: admin
    secureJsonData:
      basicAuthPassword: test123
    jsonData:
      defaultDatabase: analytics
      username: admin
      timeout: 10
    editable: true
